<a href="https://colab.research.google.com/github/gabrielbfurin/CP2_2semestre_SERS/blob/main/CP2_2semestre_SERS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Preparando o ambiente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Algoritmo de calssificação ---> regressão logística ---> entrega a probabilidade das classes
# 0: stable ---> 1: unstable
# registro A ---> [0.98 , 0.02] ---> 0
# registro B ---> [0.64 , 0.36] ---> 0
# registro C ---> [0.49 , 0.51] ---> 1

from sklearn.linear_model import LogisticRegression

# Separação dos dados para treinamento e para teste (train-test split)
from sklearn.model_selection import train_test_split

# métrica de avaliação
from sklearn.metrics import accuracy_score

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/gabrielbfurin/CP2_2semestre_SERS/refs/heads/main/Data_for_UCI_named.csv")
df.head()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,unstable
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,stable
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,unstable
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,unstable
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,unstable

In [7]:
df.shape

(10000, 14)

In [6]:
# Features
x = df.drop(columns = ['stab', 'stabf'], axis=1)
x.head()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923

In [8]:
# Target (stable ou unstable)
y = df['stabf']
y.head()

0    unstable
1      stable
2    unstable
3    unstable
4    unstable
Name: stabf, dtype: object

In [17]:
# Quais classes temos na coluna alvo???
df['stabf'].unique()

array(['unstable', 'stable'], dtype=object)

In [18]:
# Quantos registros temos na coluna alvo?
df['stabf'].value_counts()

stabf
unstable    6380
stable      3620
Name: count, dtype: int64

In [10]:
# Separação de dados de treino e teste

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [11]:
x.shape

(10000, 12)

In [14]:
x_train.shape

(2000, 12)

In [15]:
x_test.shape

(2000, 12)